### ISSUE TITLE
Problem sourcing the spaceship-promt theme

### ISSUE THREAD

**Issue by trimclain** [zap-zsh/zap#118]
### Describe the bug

I tried installing the spaceship-promt theme and got the message that it wasn't activated. After going through the code I found out,
that when zap sources the plugin, it uses the plugin name and the extension to find the file to source. In case of spaceship-promt the file is actually called spaceship.zsh-theme.

### Steps to reproduce

plug "spaceship-prompt/spaceship-prompt"

### Expected behavior

Install and enable the theme

### OS / Linux distribution

Ubuntu 22.04

### Zsh version

5.8.1

### Zap version

v0.2.0 on commit 3564bef

### Terminal emulator

kitty

### If using WSL on Windows, which version of WSL

None

**Comment by trimclain** [comment]
I just found your note about this in the README.
Are you interested in fixing this issue? I could try to do it.

**Comment by mamaraddio** [comment]
Sure, try it and do a pull request.
We will look at your code
