### ISSUE TITLE
Zsh opens to / instead of $PWD when using systemd-homed with subvolume storage

### ISSUE THREAD

**Issue by thomascft** [zap-zsh/zap#120]
### Describe the bug

I'be been having an odd issue with zsh lately. I use WezTerm as my choice terminal emulator running zsh. I can open wezterm and zsh opens in my home directory, after that I'll click new tab or run zsh in my current session. The child instance opens to / instead, and the same issue happens in the tty. I've noticed it only happens when my /zshrc contains plug lines. If I remove them it no longer has the issue with opening to /. I've also tested it in a vm and had the same issue. You can find my zsh configuration on my dotfiles repo under the zsh folder.

### Steps to reproduce

Create a systemd-homed user using subvolume storage and use https://raw.githubusercontent.com/thomascft/dotfiles/stow/zsh/.zshrc

### Expected behavior

Zsh should open to $PWD

### OS / Linux distribution

Arch Linux

### Zsh version

5.9

### Zap version

v0.2.0 on commit ca9e52d

### Terminal emulator

Wezterm

### If using WSL on Windows, which version of WSL

None

### Additional context

~~I don't have any issues on zplug~~ I'm showing similar issues under zplug, not sure where to post though

**Comment by wintermi** [comment]
Could you please reconfirm if this issue still occurs with the latest version of Zap.
