### ISSUE TITLE
Support .zshenv

### ISSUE THREAD

**Issue by gonzus** [zap-zsh/zap#134]
I don't have a `~/.zshrc` file, I have a `~/.zshenv` file with this in it:
```zsh           
export ZDOTDIR="$HOME/.config/zsh"
```
so that all my zsh configuration files live in `~/.config/zsh`, including my `.zshrc`. Zap does not seem to support this setup.

**Comment by mamaraddio** [comment]
I use the same setup and Zap works like a charm.

The problem here could be that your zshrc file haven't the `.` in front,
let me address it.

**Comment by wintermi** [comment]
I was looking through your `dotfiles` repos and do not see any issue which would cause Zap to fail.   I did see a potential issue with the install script, though that could be easily fixed, but would not cause a failure.

**Comment by gonzus** [comment]
Just to clarify, my `dotfiles` repo is probably not up to date.

My file does have the `.` to begin with:
```sh
$ cat .zshenv
export ZDOTDIR="$HOME/.config/zsh"
$ ls -al "$HOME/.config/zsh/"
total 2376
drwxr-xr-x  18 gonzo  staff   576B Apr 30 16:53 ./
drwxr-xr-x   4 gonzo  staff   128B Jan 26 11:13 ../
drwx------@  3 gonzo  staff    96B Jan  3 14:08 .zcompcache/
-rw-r--r--@  1 gonzo  staff    48K Mar 28 13:24 .zcompdump
-rw-------@  1 gonzo  staff   146B Apr  4 17:51 .zsh_history
drwx------   5 gonzo  staff   160B Apr  4 17:51 .zsh_sessions/
-rw-r--r--@  1 gonzo  staff   355B Dec  2 08:59 .zshrc
...
`

**Comment by mamaraddio** [comment]
I recommend  you to follow issue template for issues like that, anyway:
- Please answer to the **wintermi**'s question
- Are you able to run `zap version`?
  - If yes, what the output of the previous command?
  - If not, are you able to `source ~/.local/share/zap/zap.zsh`

**Comment by gonzus** [comment]
The install seems to happen correctly, but zap doesn't work afterwards:
```zsh
$ zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1
Zap is already installed in '/Users/gonzo/.local/share/zap'!
Reinstall Zap? [y/N] y
Reinstalling Zap...
Moved .zshrc to .zshrc_2023-05-03_1683119075

 Zapped
Find more plugins at http://zapzsh.org
⚡ Zap installed zsh-autosuggestions
⚡ Zap installed supercharge
⚡ Zap installed zap-prompt
⚡ Zap installed zsh-syntax-highlighting
⚡ 15:04 Wed 03/May gonzo@gonzo-mbp ~ 
$ 
⚡ 15:04 Wed 03/May gonzo@gonzo-mbp ~ 
$ zap version                                                                                        
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
⚡ Zap v
Branch:	release-v1
Commit:	
```

**Comment by mamaraddio** [comment]
Please do a
```zsh
rm -rf ~/.local/share/zap
zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh)
```

This will completely uninstall Zap and reinstall it but without pinning it to the specific branch, there where many changes in last day.

Please try that version and let us know if it works

**Comment by wintermi** [comment]
PR #138 rectifies the issue with `zap version` failing.

**Comment by wintermi** [comment]
Please retest @gonzus and if you see any further issues please reopen.

**Comment by gonzus** [comment]
All looking good, thanks!
