### ISSUE TITLE
RFC: Nvim like setup function standard for zap plugin ecosystem

### ISSUE THREAD

**Issue by yavko** [zap-zsh/zap#14]
I know this may sound unorthodox, but it would provide easy ways to provide config instead of having vars set in random places, and control when plugins are loaded.
An example:
```zsh
zapplug "plugin" # Loads plugin
plugin_name::setup arg arg2 # setup plugin
# could also be a bash associative array
```

and the plugin could look like so
```zsh
plugin_name::setup() {
	local some_arg=$1 # load arguments
	local args=$@ # load all args
	do_something_with_args somearg args # do something with them
}
```

Some people may not like this but hey its just my idea ;)

**Comment by ChristianChiarulli** [comment]
I think this might be too big of a paradigm shift atm
