### ISSUE TITLE
install.sh: ZSH(<5.8): main:zparseopts:17: no default array defined: -F

### ISSUE THREAD

**Issue by mar4th3** [zap-zsh/zap#169]
### Describe the bug

Running `install.zsh` on older versions of zsh (<5.8) throws the following error

```bash
main:zparseopts:17: no default array defined: -F
```
My knowledge of zsh is very limitied so I am unable to propose a principled fix.

Removing the `-F` options seems to work for me.

[Here](https://github.com/marlonrichert/zsh-edit/issues/7) a similar issue (w/ possible fix) 

### Steps to reproduce

- Install zsh==5.6
- zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1

### Expected behavior

Instalation should go finish w/o errors

### OS / Linux distribution

openSUSE Leap (15.3)

### Zsh version

5.6

### Zap version

release-v1O

### Terminal emulator

kitty

### If using WSL on Windows, which version of WSL

None

**Comment by wintermi** [comment]
Thanks @mar4th3 for raising this issue.  A pull request has been submitted with the fix.

**Comment by wintermi** [comment]
Pull Request merged, please reopen this issue should you continue to have a problem with the install.
