### ISSUE TITLE
Website zap outlet does not show entries

### ISSUE THREAD

**Issue by camina-apps** [zap-zsh/zap#171]
### Describe the bug

I want to see all the plugins I can install. 
But the "zap outlet" container for the plugins is empty.
I tried Firefox and Chrome with the same outcome.

### Steps to reproduce

1. open linked project website
2. scroll to bottom 

### Expected behavior

see all available plugins in Zap outlet 

### OS / Linux distribution

Linux

### Zsh version

5.6

### Zap version

v1.2.0

### Terminal emulator

kitty

### If using WSL on Windows, which version of WSL

None

**Comment by reaper8055** [comment]
I am also facing the same issue, not sure why. Chrome console shows the following:

```
core@v5.0.0-qb8w1CDc8GFGwpCOchYZ?from=@octokit/rest:19 [Package Error] "@octokit/core@v5.0.0" could not be built. (Imported by "@octokit/rest").
[1/5] Verifying package is valid…
[2/5] Installing dependencies from npm…
[3/5] Building package using esinstall…
Running esinstall...
Failed to load node_modules/@octokit/core/dist-web/index.js
  Unexpected token (13:9) in @octokit/core/dist-web/index.js
Install failed.
Install failed.
```
and
```
Uncaught Error: [Package Error] "@octokit/core@v5.0.0" could not be built. (Imported by "@octokit/rest").
    at core@v5.0.0-qb8w1CDc8GFGwpCOchYZ?from=@octokit/rest:20:7
```

**Comment by wintermi** [comment]
I see the same issue and error message in the console.  The timing of when this stopped working lines up with the release of the v5.0.0 of octokit/core, so potentially related.  @santigo-zero are you ok to investigate?

**Comment by santigo-zero** [comment]
I'll give it a look.

**Comment by santigo-zero** [comment]
I'm getting rate limited just by testing it, but it should be working now, the CDN that we were using to load Octokit has been deprecated so it couldn't be loaded.

**Comment by wintermi** [comment]
Thanks @santigo-zero

**Comment by camina-apps** [comment]
Nice, thanks @santigo-zero. Now I can start to install some helpful plugins
