### ISSUE TITLE
Can't Uninstall - Zap command still available

### ISSUE THREAD

**Issue by Normanras** [zap-zsh/zap#173]
### Describe the bug

I loaded up Zap late last week and thought it was really smooth and working well. This morning I noticed ZSH going really slowly and decided to test and remove a few plugins. This is a different issue from this bug, but when I ran `zap list`, I noticed it was listing the 4 plugins I had 998 times. 

So I decided to remove ZAP according to the instructions, but I noticed I could still run `zap help`. 

For context, I have all my dotfiles in `~/.dotfiles/zsh` and I'm using Stow to place them in my `~/` directory. I'm not sure if this is causing the issue as I know that Zap creates a new `.zshrc` in my home directory despite my dotfiles file being symlinked there. I removed both the renamed and the new zshrc files and re-symlinked back to my home directory, but that didn't seem to make anything better. It's like Zap couldn't read my `.zshrc` - I would comment out plugins and run `zap clean` and it responded with `Nothing to clean`. 

### Steps to reproduce

Honestly, not entirely sure what happened. Here's what I would try to reproduce:
1. Store your .zshrc in `~/.dotfiles/zsh/.zshrc` and use Stow/symlinks to put it in your home directory. 
2. Install ZAP
3. Adjust `.zshrc` to add some plugins. 
4. Try to uninstall zap using the documentation

### Expected behavior

I expect the zap command to no longer be available. 

### Screenshots and recordings

Running `which zap` outputs this:
```
zap () {
        typeset -A subcmds=(clean "_zap_clean" help "_zap_help" list "_zap_list" update "_zap_update" version "_zap_version")
        emulate -L zsh
        [[ -z "$subcmds[$1]" ]] && {
                _zap_help
                return 1
        } || ${subcmds[$1]} $2
}
```

I can't tell where this lives, though. 

### OS / Linux distribution

MacOS 13.5.2

### Zsh version

5.9

### Zap version

/

### Terminal emulator

WezTerm

### If using WSL on Windows, which version of WSL

None

**Comment by mamaraddio** [comment]
After uninstalling Zap have you tried to reload your shell or close and reopen the terminal?
