### ISSUE TITLE
Asyncronously Updating plugins

### ISSUE THREAD

**Issue by ckangnz** [zap-zsh/zap#178]
### If the feature solves a problem you have, specify it here.

I find updating the plugins slow. When `zap update` command runs, I expect zap and all other plugins to update automatically and asyncronously.

### Describe the proposed feature.

I want the plugins to asynchronously check its update status and update. This is a normal behaviour on `zplug` which I used before migrating to zap.

**Comment by ChristianChiarulli** [comment]
Async updates would be nice, I would weigh that against further complicating the code tho.
