### ISSUE TITLE
.zshrc content deleted when installing zap

### ISSUE THREAD

**Issue by davideLarosa** [zap-zsh/zap#184]
### Describe the bug

Hi all,
i'm not pretty sure this is a bug or a wanted condition but when i installed zap i've immediately noticed that my zsh aspect was "different" taking a look into the .zshrc file the content is just

```bash
⚡➜ ~ cat .zshrc 
# Created by Zap installer
[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ] && source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"
plug "zsh-users/zsh-autosuggestions"
plug "zap-zsh/supercharge"
plug "zap-zsh/zap-prompt"
plug "zsh-users/zsh-syntax-highlighting"
plug "esc/conda-zsh-completion"

# Load and initialise completion system
autoload -Uz compinit
compinit

```
I was wondering to have the same snippet of code in the end of my current .zshrc not to completely overwrite it.

I've seen that at least the .zshrc backup has been created.

Thank you.
Cheers

### Steps to reproduce

1. install zap with 
```bash
zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1
```
2. cat .zshrc

### Expected behavior

Not to lose the content of .zshrc

### OS / Linux distribution

OS: Arch Linux x86_64 Kernel: 6.8.9-arch1-2 

### Zsh version

zsh 5.9 (x86_64-pc-linux-gnu)

### Zap version

Version: release-v1/1.2.3 Commit Hash: d8e74d3 (5 weeks ago)

### Terminal emulator

terminator 2.1.3

### If using WSL on Windows, which version of WSL

None

**Comment by robbymoses** [comment]
This is default behavior. You can pass -k as an argument to keep your existing .zshrc and not overwrite it.
