### ISSUE TITLE
zapcmp fails on zsh-users/zsh-completions

### ISSUE THREAD

**Issue by simsrw73** [zap-zsh/zap#19]
The structure of files/directories isn't that expected by the function. 

Also, should zapcmp be zapcomp? It's more consistent with zsh: compinit, compdef, etc. And cmp always means compare to me, not complete.

**Comment by ChristianChiarulli** [comment]
we may try to roll all of the functionality into just zapplug

**Comment by ChristianChiarulli** [comment]
does it work with zapplug?

**Comment by mamaraddio** [comment]
Yeah, also do I had that issue and I solved calling
```sh
zapplug "zsh-users/zsh-completions" && compinit
```
