### ISSUE TITLE
need completion options for the zap command

### ISSUE THREAD

**Issue by ChristianChiarulli** [zap-zsh/zap#22]

**Comment by bagm4n** [comment]
```shell
#compdef zap

_arguments -C -s \
  "(-)"{-h,--help}"[Show help information]" \
  "(-)"{-v,--version}"[Show version information]" \
  "1: :(update delete pause unpause)"
```
This is how it looks:

![image](https://user-images.githubusercontent.com/117671660/201411655-0ff840c2-9447-4fcf-be37-4bd6408fa0a6.png)

![image](https://user-images.githubusercontent.com/117671660/201411272-28a11a5a-7ba0-45c7-bf39-38e37982882d.png)

**Comment by ChristianChiarulli** [comment]
should this be a plugin?

**Comment by Granddave** [comment]
I think it would be good to have completion for the core included in the main repo so that they don't get out of sync which is a risk having them separated :)
