### ISSUE TITLE
Need a logo, please add ideas here

### ISSUE THREAD

**Issue by ChristianChiarulli** [zap-zsh/zap#3]
see title

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/200197993-81c88dbe-4743-4856-a027-967eb1ee2078.png)

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/200199028-7facb011-6003-4722-b044-3cdbf7f033e0.png)

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/200203037-910a9c7a-8888-4e8a-aed5-7101f36da834.png)

**Comment by S1M0N38** [comment]
![zap-logo](https://user-images.githubusercontent.com/22257750/200391560-85cdc922-8a8c-45ea-8db6-d4218b64560b.png)

**Comment by webservices-network** [comment]
![image](https://user-images.githubusercontent.com/113269656/200907814-a44aa147-99c0-4c07-bc8d-200da80b476b.png)

**Comment by webservices-network** [comment]
![image](https://user-images.githubusercontent.com/113269656/200939177-745408f8-9914-45ed-a69f-a4e1993442ba.png)

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/201484610-db5889aa-2fc4-4449-914e-3d4e3bdf7014.png)

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/202043505-8fda8d1e-3669-463b-a0c9-38c367ffb753.png)

**Comment by anoduck** [comment]
> ![zap-logo](https://user-images.githubusercontent.com/22257750/200391560-85cdc922-8a8c-45ea-8db6-d4218b64560b.png)

To me, this read "ZHP", not "ZAP"

**Comment by Burnsedia** [comment]
I can make a 3d version of the logo. I just need a SVG

**Comment by Burnsedia** [comment]
> ![image](https://user-images.githubusercontent.com/29136904/202043505-8fda8d1e-3669-463b-a0c9-38c367ffb753.png)
3d version coming up

**Comment by anoduck** [comment]
> > ![image](https://user-images.githubusercontent.com/29136904/202043505-8fda8d1e-3669-463b-a0c9-38c367ffb753.png)
> > 3d version coming up

I believe this will look really good.

**Comment by Burnsedia** [comment]
@anoduck @ChristianChiarulli I am converting this to an SVG and then Turning it into a 3d model; maybe we can have a threejs based 3d animated logo

**Comment by ChristianChiarulli** [comment]
![zap_yt_thumbnail](https://github.com/zap-zsh/zap/assets/29136904/b6201b3f-bf85-4866-95f3-df275cc94759)

**Comment by ChristianChiarulli** [comment]
![zap_yt_thumbnail_play_button](https://github.com/zap-zsh/zap/assets/29136904/943e3f25-5198-45a5-a22e-45a3a27db11d)
