### ISSUE TITLE
Install to $ZDOTDIR/zap

### ISSUE THREAD

**Issue by DitchComfort** [zap-zsh/zap#30]
I know you said it was possible to install to $ZDOTDIR, but that's only to source the .zshrc if it's located there.

I want to be able to install the entire plugin manager to e.g. ${ZDOTDIR:-$HOME/.config/zsh}/zap
I don't want to have ZAP_DIR in $HOME/.local/share/zap

**Comment by ChristianChiarulli** [comment]
hmm, we could probably change that in the installer, not sure why you'd want the plugin manager in your config folder tho

**Comment by DitchComfort** [comment]
Just nice to have everything zsh-related in the same folder, but I don't know... I'm also used to using Zap (before it became the plugin manager) and having my plugins directory in ~/.config/zsh/plugins. Was just a suggestion, I can get used to .local/share/zap

**Comment by ChristianChiarulli** [comment]
I don't think we should install zap to ZDOTDIR maybe in the future we can let the user choose any installation dir they want but it's not really a priority nor should it be encouraged to break the conventional standards.
