### ISSUE TITLE
bug: pause and unpause not working on macOS

### ISSUE THREAD

**Issue by ChristianChiarulli** [zap-zsh/zap#35]
![image](https://user-images.githubusercontent.com/29136904/201365460-d7265037-3452-451a-8c3d-2a4a69c034b4.png)

**Comment by Pheon-Dev** [comment]
Did it work prior to #29?@ChristianChiarulli

**Comment by ChristianChiarulli** [comment]
@Pheon-Dev not sure, didn't check on my mac then, still haven't checked if it's currently working on linux

**Comment by Pheon-Dev** [comment]
I'm using linux, didn't try it on Mac

**Comment by ChristianChiarulli** [comment]
https://guideshaven.com/how-to-solve-sed-1-filename-command-c-expects-followed-by-text/

There is a different `sed` on mac based on BSD
