### ISSUE TITLE
bug: update is broken new plug

### ISSUE THREAD

**Issue by AntPeixe** [zap-zsh/zap#37]
#36 breaks plugin update as it changes the structure of the `plugins` folder, from `plugins/<plugin_name>`  to `plugins/<user>/<plugin_name>` 

It also breaks the list of plugins to update, it shows the user instead of the plugin name.

Not sure which way should be chosen.

**Comment by Pheon-Dev** [comment]
Yes, that should be looked into.

**Comment by ChristianChiarulli** [comment]
this should be fixed pls pull the latest and check

**Comment by AntPeixe** [comment]
looking at the commit it seems like you reverted the merge from the linked PR.

Seems to be working again for me. I guess we can close this then.
