### ISSUE TITLE
Defining function based on alias update

### ISSUE THREAD

**Issue by jrock2004** [zap-zsh/zap#39]
Trying to set up on my M1 mac and when I source `zap.zsh` I get errors

```
source "$HOME/.local/share/zap/zap.zsh"
/Users/John.Costanzo/.local/share/zap/zap.zsh:42: defining function based on alias `update'
/Users/John.Costanzo/.local/share/zap/zap.zsh:42: parse error near `()'
```

**Comment by jrock2004** [comment]
Maybe this is related to #37

**Comment by Pheon-Dev** [comment]
Yes it is. The plugins folder has been further subdivided to user specific i.e plugin creators

**Comment by jrock2004** [comment]
Should PR be reverted till solution is found?

**Comment by ChristianChiarulli** [comment]
we should probably revert this decide whether or not we want to keep it this way

**Comment by Granddave** [comment]
I'm working on getting CI going to check formatting. #38 
Would be nice to have a test suite to test that all functionality is working as it should as well. :)

**Comment by ChristianChiarulli** [comment]
this should be fixed, can someone check?

**Comment by jrock2004** [comment]
@ChristianChiarulli just tried. Ran the remove command and ran installer command and still same issue

**Comment by ChristianChiarulli** [comment]
Are you sure you hav the latest?
![image](https://user-images.githubusercontent.com/29136904/201444261-549caefd-2e7b-4112-ab26-b557892752cb.png)
Everything seems to work for me

**Comment by jrock2004** [comment]
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/655716/201449002-d3aef5e1-4c59-4209-8a61-f8f052840ce9.png">

I removed the directory so not sure who I could not get the newest

**Comment by ChristianChiarulli** [comment]
we recently renamed zapplug to just plug

**Comment by jrock2004** [comment]
Getting progress, about zapcmp

**Comment by jrock2004** [comment]
Ah forget, readme show to just use plug for everything

**Comment by jrock2004** [comment]
Another thing to mention is the function you expose to system path like update might collide if users already have something with a name. Example 

```
if dotfiles::exists apt-get ; then
  alias update='sudo apt-get update && sudo apt-get upgrade'
elif dotfiles::exists brew ; then
  alias update='brew update && brew upgrade && brew doctor'
elif dotfiles::exists paru ; then
  alias update='paru -Syu'
elif dotfiles::exists pacman ; then
  alias update='sudo pacman -Syu'
fi
```
