### ISSUE TITLE
bug: local file should not show in update list

### ISSUE THREAD

**Issue by ChristianChiarulli** [zap-zsh/zap#51]
![image](https://user-images.githubusercontent.com/29136904/201496428-af65647d-e3ca-4865-bbb8-39117328045c.png)

**Comment by Pheon-Dev** [comment]
Looking into it

**Comment by ChristianChiarulli** [comment]
![image](https://user-images.githubusercontent.com/29136904/201499699-380cdc13-96d9-4a30-b0bd-13e7c84ea1c9.png)

**Comment by Pheon-Dev** [comment]
Did it fix?

**Comment by ChristianChiarulli** [comment]
yea but now we have another problem lol https://github.com/zap-zsh/zap/issues/58
