### ISSUE TITLE
Do not ask for user input in (de)activate if there is nothing to do

### ISSUE THREAD

**Issue by AntPeixe** [zap-zsh/zap#53]
If all plugins are active then it shouldn't ask for input when running activate and similarly for deactivate.

**Comment by Pheon-Dev** [comment]
Use case:

If one has different prompts for example, one can just run zap -a and activate one among unused plugins and zap -d to deactivate one among other used plugins. 

Scenarios may vary but it maybe deemed necessary once one has a plethora of plugins and is trying to debug by activating and deactivating one by one

**Comment by AntPeixe** [comment]
But that use case seems to be the expected one, no?

What I'm suggesting is that if you have all plugins active and you run `zap -a` you shouldn't be prompted to choose a plugin (or all). IMO it should instead just inform that all plugins are active.

Current behavior:
![image](https://user-images.githubusercontent.com/21229140/201498945-48c03482-f99e-453a-bc08-5324f65802bc.png)

**Comment by Pheon-Dev** [comment]
Yeah, that should definitely be considered. 

I thought you only meant two options like it was before (pause || unpause), where you'd only either (de)activate all plugins with no option for cherry picking.
