### ISSUE TITLE
bug: some plugins not showing in update menu

### ISSUE THREAD

**Issue by ChristianChiarulli** [zap-zsh/zap#58]
![image](https://user-images.githubusercontent.com/29136904/201499782-1bb13eec-f772-4b7b-ba43-3cd4cfad5085.png)

**Comment by ChristianChiarulli** [comment]
only happening on macOS

**Comment by Pheon-Dev** [comment]
Could be double or single quotes mixup for different plugins. Speaking of, is "zap -i,--install GitHub-URL" a viable option? @ChristianChiarulli
