### ISSUE TITLE
$ZDOTDIR not being read properly? 

### ISSUE THREAD

**Issue by Selmer443** [zap-zsh/zap#70]
my ZDOTDIR is set in .zshenv file in home directory, when running the command on zap website another .zshrc was created in home directory with commands to source zap. I'm assuming this was likely because ZDOTDIR was not picked up by the install script?

**Comment by Senpai-10** [comment]
@Selmer443 export `ZDOTDIR` in your .zshrc

```bash
export ZDOTDIR="path/to/zsh_config_dir"
```

**Comment by Senpai-10** [comment]
I tried to reproduce the same issue, and found it comes from not exporting `ZDOTDIR`

**Comment by DitchComfort** [comment]
I have my .zshenv symlinked to $HOME
and I only have the following commands, and no need to export anything in .zshenv

\# The new re-$HOME-ing variable
: ${XDG_CONFIG_HOME:=$HOME/.config}

\# ZDOTDIR is a zsh-ism (natively supported)...
\# but it's a really cool concept.
\# Zsh use the parameter name ZDOTDIR when looking
\# for core start-up files, defaulting to $HOME if it's not set.
ZDOTDIR=$XDG_CONFIG_HOME/zsh

**Comment by undg** [comment]
To make that work in `install.sh` I've changed shebang to `#!/bin/env zsh`. Without that `$ZDOTDIR` can't be read from `.zshenv`.

**Comment by mamaraddio** [comment]
Anyone can confirm that after #92 was merged it works? So I'll close this issue
