### ISSUE TITLE
zsh-history-substring-search not working.

### ISSUE THREAD

**Issue by cronyakatsuki** [zap-zsh/zap#71]
zsh-history-substring-search trows this error
```
_history-substring-search-up-history:zle:13: widgets can only be called when ZLE is active
zsh-syntax-highlighting: error: $region_highlight is not defined
zsh-syntax-highlighting: (Check whether zsh-syntax-highlighting was installed according to the instructions.)
```
> end of my config
```
[ -f "$HOME/.local/share/zap/zap.zsh" ] && source "$HOME/.local/share/zap/zap.zsh"

plug "zsh-users/zsh-autosuggestions"
plug "zsh-users/zsh-syntax-highlighting"
plug "zsh-users/zsh-history-substring-search"
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
```
According to the instructions it should be loaded after syntax plugin which it is but it is not working the way it should.
Using the keybindings just goes up normally and highlight the part of text searched for example `his` only when it comes in history.

**Comment by AntPeixe** [comment]
I use both of those plugins and for me it's working fine.

Have you configured the settings for the history?
What other plugins are you running? Did you try disabling them and use only these two?

If you're using zap-zsh/supercharge check this [issue](https://github.com/zap-zsh/supercharge/issues/6) you may be missing some of the settings. I've left them as suggestions but maybe it's added to the plugin.

**Comment by cronyakatsuki** [comment]
No those are all my plugins I had loaded. [https://github.com/cronyakatsuki/arch-dots/blob/main/.config/zsh/.zshrc](zshrc).
This is still an older version of the config but all I did was replace the plugins section with one I provided in the bug report and move all below it before the plugins section.

**Comment by mamaraddio** [comment]
Someone still has this issue? I tried on my config and it works

I bonded  history-substring-search-up/down with <kbd>UpArrow</kbd> / <kbd>DownArrow</kbd>

![image](https://user-images.githubusercontent.com/82162277/212665677-764d284c-a4ee-439b-bf91-b20a396b82ea.png)

![image](https://user-images.githubusercontent.com/82162277/212664763-5f3832ab-a387-400b-b24e-375d0ce6c28a.png)

![image](https://user-images.githubusercontent.com/82162277/212664838-5b9893fc-fce5-4b3c-adef-a07756080cde.png)
