### ISSUE TITLE
no such file or directory: /home/$USER/.local/share/zap/installed_plugins

### ISSUE THREAD

**Issue by The-0Day** [zap-zsh/zap#89]
After adding the following lines to `.zshrc`, I got:
```
plug:26: no such file or directory: /home/$USER/.local/share/zap/installed_plugins
plug:26: no such file or directory: /home/$USER/.local/share/zap/installed_plugins
plug:26: no such file or directory: /home/$USER/.local/share/zap/installed_plugins
plug:26: no such file or directory: /home/$USER/.local/share/zap/installed_plugins
plug:26: no such file or directory: /home/$USER/.local/share/zap/installed_plugins
```
The problem was fixed by commenting 50-52 in `$ZAP_DIR/zap.zsh`.

**Comment by eyzab** [comment]
Hi @The-0Day, do you have any steps to replicate the issue and a minimal user configuration?

**Comment by The-0Day** [comment]
> Hi @The-0Day, do you have any steps to replicate the issue and a minimal user configuration?

This issue fixed. `zap` works fine now.

**Comment by wintermi** [comment]
Closing the issue as the issue author responded that this is now fixed.

**Comment by mamaraddio** [comment]
The user solved the issue by commenting 3 lines in the zap codebase loosing the abilityto use `zap --clean`,
so he doesn't really solved it.
I hope #100 will solve the issue
