### ISSUE TITLE
Tab Completion Error

### ISSUE THREAD

**Issue by Pheon-Dev** [zap-zsh/zap#9]
When pressing the Tab key for auto complete, this error occurs
![Picture_3](https://user-images.githubusercontent.com/93865776/200371391-560ddf52-8825-4cd5-8024-46bd7b7d62ab.png)

**Comment by ChristianChiarulli** [comment]
weird, what plugins are installed?

**Comment by Pheon-Dev** [comment]
Resolved it, I had other colliding plugins sourced in my zshrc, it now works as expected when commented out and only using zaps native
